### ISSUE TITLE
请问：有调用链形式的数据记录吗？

### ISSUE THREAD

**Issue by lifw555** [ThinkpadNC5/MyPerf4J#11]
比如：a方法，调用b，c，d方法，b调用e方法，展现的形式就是以缩进（或标号1.1;1.1.1,1,2,1.3）的形式展示

`MyPerf4J Performance Statistics [2018-07-01 23:40:23, 2018-07-01 23:40:24]

chain Api[2/3]                    RPS  Avg(ms)  Min(ms)  Max(ms)   StdDev     Count     TP50     TP90     TP95     TP99    TP999   TP9999  TP99999    TP100

1    DemoServiceImpl.getId1  7454181     0.00        0        0     0.00   7454181        0        0        0        0        0        0        0        0

1.1 DemoServiceImpl.getId2  7454180     0.00        0        0     0.00   7454180        0        0        0        0        0        0        0        0`

**Comment by lifw555** [comment]
`MyPerf4J Performance Statistics [2018-07-01 23:40:23, 2018-07-01 23:40:24]
chain Api[2/3]                    RPS  Avg(ms)  Min(ms)  Max(ms)   StdDev     Count     TP50     TP90     TP95     TP99    TP999   TP9999  TP99999    TP100`
1    DemoServiceImpl.getId1  7454181     0.00        0        0     0.00   7454181        0        0        0        0        0        0        0        0
1.1 DemoServiceImpl.getId2  7454180     0.00        0        0     0.00   7454180        0        0        0        0        0        0        0        0`

**Comment by lifw555** [comment]
格式化代码功能不好用。

**Comment by ThinkpadNC5** [comment]
抱歉，MyPerf4J并不支持记录方法调用次序，MyPerf4J的定位是统计性能数据，并非链路追踪。

如果需要观察调用链路上的耗时，可以尝试Pinpoint等全链路追踪工具 : )

**Comment by lifw555** [comment]
OK！收到。
