### ISSUE TITLE
请问为什么Method Metrics没有数据？

### ISSUE THREAD

**Issue by 136908359** [ThinkpadNC5/MyPerf4J#23]
**Bug 描述** 
请清晰和简洁的描述你遇见的 bug
安装后其他的指标都有数据，但是java日志里Method Metrics一直没有数据返回
**运行环境**
1、JDK 版本号，例如，JDK7、JDK8 等 
2、运行容器和框架，例如，Tomcat、PlainJava、Spring、SpringBoot 等
SpringBoot，JDK8
**配置文件** 
请把你的配置文件内容完整的复制出来
#应用名称
AppName=risk-1.0.0.jar

#配置MetricsProcessors，可不配置
#MethodMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBMethodMetricsProcessor
#ClassMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBJvmClassMetricsProcessor
#GCMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBJvmGCMetricsProcessor
#MemMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBJvmMemoryMetricsProcessor
#ThreadMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBJvmThreadMetricsProcessor

MetricsProcessorType=2

#配置各个Metrics日志的文件路径，可不配置
MethodMetricsFile=/tmp/MyPerf4J/method_metrics.log
ClassMetricsFile=/tmp/MyPerf4J/class_metrics.log
GCMetricsFile=/tmp/MyPerf4J/gc_metrics.log
MemMetricsFile=/tmp/MyPerf4J/memory_metrics.log
BufPoolMetricsFile=/tmp/MyPerf4J/buf_pool_metrics.log
ThreadMetricsFile=/tmp/MyPerf4J/thread_metrics.log

#配置备份Recorders的数量，默认为1，最小为1，最大为8，当需要在较小MillTimeSlice内统计大量方法性能数据时可配置大一些
BackupRecordersCount=1

#配置Record模式，可配置为accurate/rough
RecorderMode=rough

#配置时间片，单位为ms，最小1s，最大600s
MillTimeSlice=10000

#需要监控的package，可配置多个，用英文';'分隔
IncludePackages=risk-1.0.0.jar

#不需要监控的package，可配置多个，用英文';'分隔
#ExcludePackages=org.spring;

#可配置多个方法名，用英文';'分隔
ExcludeMethods=equals;hash

#是否排除私有方法，true/false
ExcludePrivateMethod=true

#通用的方法执行时间阈值，单位为ms
ProfilingTimeThreshold=1000

#在一个时间片内，超过方法执行时间阈值的次数，仅在RecorderMode=accurate时有效
ProfilingOutThresholdCount=10
**异常堆栈** 
请把程序的错误栈信息完整的复制出来
MyPerf4J JVM Class Metrics [2018-11-25 11:47:00, 2018-11-25 11:48:00]
Total         Loaded  Unloaded
7271            7271         0

MyPerf4J JVM GC Metrics [2018-11-25 11:47:00, 2018-11-25 11:48:00]
Name            Count     Time
PS Scavenge         6      134
PS MarkSweep        2       92

MyPerf4J JVM Memory Metrics [2018-11-25 11:47:00, 2018-11-25 11:48:00]
NonHeapInit                NonHeapUsed   NonHeapCommitted         NonHeapMax           HeapInit           HeapUsed      HeapCommitted            HeapMax
2555904                       66061400           68091904                 -1         2147483648          569814776         2089811968         2089811968

MyPerf4J JVM BufferPool Metrics [2018-11-25 11:47:00, 2018-11-25 11:48:00]
Name                             Count         MemoryUsed     MemoryCapacity
direct                               0                  0                  0
mapped                               0                  0                  0

MyPerf4J Method Metrics [2018-11-25 11:47:00, 2018-11-25 11:48:00]
Method[0]      RPS  Avg(ms)  Min(ms)  Max(ms)   StdDev     Count     TP50     TP90     TP95     TP99    TP999   TP9999  TP99999    TP100

MyPerf4J JVM Class Metrics [2018-11-25 11:48:00, 2018-11-25 11:49:00]
Total         Loaded  Unloaded
7282            7282         0

MyPerf4J JVM GC Metrics [2018-11-25 11:48:00, 2018-11-25 11:49:00]
Name            Count     Time
PS Scavenge         6      134
PS MarkSweep        2       92

MyPerf4J JVM Memory Metrics [2018-11-25 11:48:00, 2018-11-25 11:49:00]
NonHeapInit                NonHeapUsed   NonHeapCommitted         NonHeapMax           HeapInit           HeapUsed      HeapCommitted            HeapMax
2555904                       66187808           68091904                 -1         2147483648          573002480         2089811968         2089811968

MyPerf4J JVM BufferPool Metrics [2018-11-25 11:48:00, 2018-11-25 11:49:00]
Name                             Count         MemoryUsed     MemoryCapacity
direct                               0                  0                  0
mapped                               0                  0                  0

**Comment by ThinkpadNC5** [comment]
你好，你的 `IncludePackages` 配置错了，应该是 `IncludePackages=com.spring.io` 这种形式的

**Comment by 136908359** [comment]
您好，启动method还是没数据，IncludePackages已经修改了，如下：
#应用名称
AppName=-risk-1.0.0.jar

#配置MetricsProcessors，可不配置
#MethodMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBMethodMetricsProcessor
#ClassMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBJvmClassMetricsProcessor
#GCMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBJvmGCMetricsProcessor
#MemMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBJvmMemoryMetricsProcessor
#ThreadMetricsProcessor=cn.myperf4j.ext.metric.processor.influxdb.InfluxDBJvmThreadMetricsProcessor

MetricsProcessorType=2

#配置各个Metrics日志的文件路径，可不配置
MethodMetricsFile=/tmp/MyPerf4J/method_metrics.log
ClassMetricsFile=/tmp/MyPerf4J/class_metrics.log
GCMetricsFile=/tmp/MyPerf4J/gc_metrics.log
MemMetricsFile=/tmp/MyPerf4J/memory_metrics.log
BufPoolMetricsFile=/tmp/MyPerf4J/buf_pool_metrics.log
ThreadMetricsFile=/tmp/MyPerf4J/thread_metrics.log

#配置备份Recorders的数量，默认为1，最小为1，最大为8，当需要在较小MillTimeSlice内统计大量方法性能数据时可配置大一些
BackupRecordersCount=1

#配置Record模式，可配置为accurate/rough
RecorderMode=rough

#配置时间片，单位为ms，最小1s，最大600s
MillTimeSlice=10000

#需要监控的package，可配置多个，用英文';'分隔
IncludePackages=org.springframework.boot

#不需要监控的package，可配置多个，用英文';'分隔
#ExcludePackages=org.spring;

#可配置多个方法名，用英文';'分隔
#ExcludeMethods=equals;hash

#是否排除私有方法，true/false
ExcludePrivateMethod=false

#通用的方法执行时间阈值，单位为ms
ProfilingTimeThreshold=1000

#在一个时间片内，超过方法执行时间阈值的次数，仅在RecorderMode=accurate时有效
ProfilingOutThresholdCount=10

Debug.PrintDebugLog=true


谢谢！

**Comment by 136908359** [comment]
这是jar包里的部分内容：
org/springframework/boot/loader/archive/JarFileArchive$EntryIterator.class
org/springframework/boot/loader/archive/ExplodedArchive$FileEntryIterator.class
org/springframework/boot/loader/archive/ExplodedArchive$FileEntry.class
org/springframework/boot/loader/archive/JarFileArchive$JarFileEntry.class
org/springframework/boot/loader/archive/Archive$Entry.class
org/springframework/boot/loader/archive/JarFileArchive.class

**Comment by ThinkpadNC5** [comment]
你好，`IncludePackages ` 代表的是需要进行性能监控的 packages，这个应该配置为你项目的 packages，为什么要监控 springboot 的代码？

PS：MyPerf4J 默认把包 `org/` 及其子包给排除了，如果确实需要监控 `org/` 包中代码的性能，可以修改 MyPerf4J 中 ProfilingFilter 类的源码。

**Comment by 136908359** [comment]
好的，谢谢，这个已经出数据了

**Comment by ThinkpadNC5** [comment]
客气

**Comment by 136908359** [comment]
不好意思，数据已经出来，但是出数据的时间间隔不对，重启一次服务出一次数据，然后就不出了，请教您一下。配置文件如下：
AppName=risk-1.0.0.jar
MetricsProcessorType=2
MethodMetricsFile=/tmp/MyPerf4J/method_metrics.log
ClassMetricsFile=/tmp/MyPerf4J/class_metrics.log
GCMetricsFile=/tmp/MyPerf4J/gc_metrics.log
MemMetricsFile=/tmp/MyPerf4J/memory_metrics.log
BufPoolMetricsFile=/tmp/MyPerf4J/buf_pool_metrics.log
ThreadMetricsFile=/tmp/MyPerf4J/thread_metrics.log
BackupRecordersCount=1
RecorderMode=rough
MillTimeSlice=10000
IncludePackages=com.bp.start
ExcludeMethods=equals;hash
ExcludePrivateMethod=true
ProfilingTimeThreshold=1000
ProfilingOutThresholdCount=10

**Comment by ThinkpadNC5** [comment]
这个，你得确保你的服务一直有访问

**Comment by 136908359** [comment]
您好，我这边都顺利了，只是还有一个grafana仪表盘上的DC是啥意思，influx都没取到这个tag啊

**Comment by ThinkpadNC5** [comment]
请看[这里](https://github.com/ThinkpadNC5/MyPerf4J/wiki/Telegraf_)
 DC：DataCenter，可以简单理解为机房，例如 Ali 或者 Tengxun
