### ISSUE TITLE
在windows下运行是否存在问题？

### ISSUE THREAD

**Issue by dufzh** [ThinkpadNC5/MyPerf4J#5]
BAT中编写启动指令如下：
java -jar SEmodbus_Server.jar -javaagent:MyPerf4J-ASM.jar -DMyPerf4JPropFile=myPerf4J.properties
配置文件中监控package配置为
IncludePackages=com.seari.modbusServer.api
其余为默认配置
SEmodbus_Server项目log4j stdout配置如下
log4j.appender.stdout = org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout = org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern =  %d %p [%c] - %m%n

运行后在console窗口中未见MyPerf4J相关日志信息

**Comment by ThinkpadNC5** [comment]
你好，在Windows 系统下也是可以正常运行的。
以下是我的几个建议：
* 请使用绝对路径的方式：
  > -javaagent:/your/path/to/MyPerf4J-ASM-${MyPerf4J-version}.jar
  >-DMyPerf4JPropFile=/your/path/to/myPerf4J.properties

* 请检查stdout.log和stderr.log
* 请设置Debug.PrintDebugLog=true

希望对你有帮助 : ）
