### ISSUE TITLE
请问可以部署在[window]环境[tomcat/lib]下吗？

### ISSUE THREAD

**Issue by WenTao-Love** [ThinkpadNC5/MyPerf4J#6]
这个真心挺牛逼的，但是要是将以前的项目加上MyPerf4J-ASM.jar,然后再写配置文件，略感工作量有点大。
于是，突发奇想，可以将MyPerf4J-ASM.jar放在tomcat下，全局生效。
我在tomcat/bin/catalina.sh文件中，配置如下
`-javaagent:%cd%\..\lib\MyPerf4J-ASM.jar
-DMyPerf4JPropFile=%cd%\..\conf\myPerf4J.properties`

在tomcat/conf/myPerf4J.properties 写
`#配置PerfStatsProcessor，可不配置，用于自定义统计数据的处理
#PerfStatsProcessor=cn.perf4j.demo.MyPerfStatsProcessor
   
#配置备份Recorders的数量，默认为1，最小为1，最大为8，当需要在较小MillTimeSlice内统计大量方法性能数据时可配置大一些
BackupRecordersCount=1
   
#配置Record模式，可配置为accurate/rough
RecorderMode=accurate
   
#配置时间片，单位为ms，最小1s，最大600s
MillTimeSlice=10000
   
#需要监控的package，可配置多个，用英文';'分隔
IncludePackages=com.chinalife.sz
   
#不需要监控的package，可配置多个，用英文';'分隔
ExcludePackages=org.spring;
   
#可配置多个方法名，用英文';'分隔
ExcludeMethods=equals;hash
   
#是否排除私有方法，true/false
ExcludePrivateMethod=true
   
#通用的方法执行时间阈值，单位为ms
ProfilingTimeThreshold=1000
   
#在一个时间片内，超过方法执行时间阈值的次数，仅在RecorderMode=accurate时有效
ProfilingOutThresholdCount=10`

然后在tomcat/logs日志里，没找到MyPerf4J相关的信息

**Comment by ThinkpadNC5** [comment]
Hi，感谢您使用MyPerf4J : )

MyPerf4J是通过读取`MyPerf4JPropFile`来解析配置文件的，目前只支持绝对路径；
其实您可以这样:
把MyPerf4J-ASM.jar和myPerf4J.properties放到/data/MyPerf4J目录下，这样只需要在JVM的启动脚本里加上:
-javaagent:/data/MyPerf4J/MyPerf4J-ASM.jar 
-DMyPerf4JPropFile=/data/MyPerf4J/myperf4J.properties
就行了，所有应用程序只需加上这两个参数即可。

希望对您有帮助: )
