### ISSUE TITLE
提个bug, ExcludePackages的问题

### ISSUE THREAD

**Issue by timestatic** [ThinkpadNC5/MyPerf4J#7]
ExcludePackages 非必填参数, 当我不设置的这个参数的时候, 或者等于空, 会发生排除掉所有的package的情况
原因是这种情况下拿到的ExcludePackages 是空字符串, 并放到了excludePackage set中, 

ProfilingFilter.isNotNeedInject的判断`innerClassName.startsWith(prefix); // prefix == ""`, 就会排除掉所有的class了
ProfilingFilter 中 add 到相应set的判断需要改下

**Comment by ThinkpadNC5** [comment]
感谢反馈，develop分支目前已修复 : )
