### ISSUE TITLE
spring启动时加载不到方法，该如何配置？

### ISSUE THREAD

**Issue by ljzzju** [ThinkpadNC5/MyPerf4J#9]
![image](https://user-images.githubusercontent.com/9129130/43575263-fd3ecbfe-9678-11e8-958b-d4cacdb7a4ed.png)

**Comment by ThinkpadNC5** [comment]
你的配置文件能发出来么？
你是用master分支还是develop 分支？现在master分支有一个bug，就是没有配置ExcludePackages时会过滤掉所有的方法，该bug已经在develop分支修复了。

**Comment by ljzzju** [comment]
@ThinkpadNC5 好了，dev分支是可以的，多谢

**Comment by ThinkpadNC5** [comment]
客气 : )
